### ISSUE TITLE
Apakah repo ini benar-benar terdaftar di hactoberfest?

### ISSUE THREAD

**Issue by Aldhanekaa** [cacadosman/Do-Whatever-You-Want#41]
jika ya, bisakah saya mengetahui buktinya

**Comment by Aldhanekaa** [comment]
why there is no Jakarta event in hacktoberfest?

**Comment by cacadosman** [comment]
Sebenarnya untuk rules dari Hacktoberfest ini sendiri, hanya perlu melakukan Pull Request di semua repository  dengan visibilitas publik.
Untuk keterangan lebih jelasnya bisa dilihat pada laman faq nya https://hacktoberfest.digitalocean.com/faq
